/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"
#include "bar.h"

#include "bar_dwmblocks.h"
#include "bar_ltsymbol.h"
#include "bar_status2d.h"
#include "bar_statuscmd.h"
#include "bar_tags.h"
#include "bar_systray.h"

/* Other patches */
#include "attachx.h"
#include "cfacts.h"
#include "cyclelayouts.h"
#include "focusmaster.h"
#include "maximize.h"
#include "mpdcontrol.h"
#include "moveresize.h"
#include "pertag.h"
#include "placemouse.h"
#include "reorganizetags.h"
#include "restartsig.h"
#include "renamed_scratchpads.h"
#include "seamless_restart.h"
#include "shift.h"
#include "shiftviewclients.h"
#include "stacker.h"
#include "sticky.h"
#include "swallow.h"
#include "swaptags.h"
#include "tagswapmon.h"
#include "tapresize.h"
#include "togglefullscreen.h"
#include "vanitygaps.h"
#include "xrdb.h"
/* Layouts */
#include "layout_flextile-deluxe.h"
#include "layout_monocle.h"
#include "layout_tile.h"

